name: GKI Kernel Module Build

on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/ci.yml"
      - "ovo/**"
  
  pull_request:
    branches: ["master"]
    paths:
      - ".github/workflows/ci.yml"
      - "ovo/**"

  workflow_dispatch:

jobs:
  build:
    name: GKI Kernel Module Build
    runs-on: ubuntu-latest
    needs: upload-artifact
    strategy:
      fail-fast: false
      matrix:
        tag:
          - android12-5.10
          - android13-5.10
          - android13-5.15
          - android14-5.15
          - android14-6.1
          - android15-6.6
          - android16-6.12
        arch:
          - aarch64

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run GKI Kernel Build Action
        uses: ./
        with:
          arch: ${{ matrix.arch }}
          tag: ${{ matrix.tag }}
          module-name: ovo
          module-path: ovo
          